# Generated by Django 5.0.2 on 2024-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPredictModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
            ],
        ),
    ]
